# Use the below command directly in the terminal to build and run the Go REST API application.
# go build -o bin/restapi cmd/main.go

build:
	@go build -o bin/restapi cmd/main.go

run: build
	@./bin/restapi

migration:
	@migrate create -ext sql -dir cmd/migrate/migrations $(filter-out $@, $(MAKECMDGOALS))

migrate-up:
	@go run cmd/migrate/main.go up

migrate-down:
	@go run cmd/migrate/main.go down
